version: "2"
services:
  node:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
    volumes:
      - ./discordbot/:/home/node/app/
    restart: always
    command: bash -c "npm install && node ."
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: project
      MONGODB_CONNSTRING: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo
    command: mongod --auth --bind_ip_all
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongo
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
#      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
#      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_ROOT_USER}
#      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
#      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
#      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
#      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/
#    depends_on:
#      - mongo
